version: '3.8'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_app:latest
    container_name: django_app
    volumes:
      - /root/logs:/app/logs # Mount a directory for logs
      - .:/app # Mount the project folder to the container
      - /root/.env:/app/.env:ro # Mount .env file into the container with read-only permission
    restart: always
    environment:
      - ENV_FILE=/app/.env
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      - ENV_FILE=/app/.env
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=library
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    volumes:
      - /root/mysql/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      - /root/mysql/data:/var/lib/mysql
      - /root/mysql/logs:/var/log/mysql # Persist MySQL data on host
    restart: always

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment: []
    ports:
      - 6380:6379 

  huey:
    build: .
    container_name: huey
    restart: always
    command: python3 manage.py run_huey
    depends_on:
      - redis
    volumes:
      - .:/app
      - /root/.env:/app/.env:ro
    environment:
      - ENV_FILE=/app/.env