# Generated by Django 5.1.4 on 2025-01-11 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_borrowedbook'),
        ('libraries', '0002_delete_branchbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.branch')),
            ],
        ),
    ]
