# Generated by Django 5.1.4 on 2025-01-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_borrowedbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='overdue_days_penalty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
