# Generated by Django 5.1.4 on 2025-01-11 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_borrowedbook_overdue_days_penalty'),
        ('libraries', '0002_delete_branchbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_branches', to='books.book'),
        ),
        migrations.AlterField(
            model_name='branchbook',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_books', to='libraries.branch'),
        ),
    ]
