# Generated by Django 5.1.4 on 2025-01-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_branchbook_book_alter_branchbook_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
